DELETE FROM country;

INSERT INTO country (co_code, co_name) VALUES ('AF', 'Afghanistan');
INSERT INTO country (co_code, co_name) VALUES ('AL', 'Albania');
INSERT INTO country (co_code, co_name) VALUES ('DZ', 'Algeria');
INSERT INTO country (co_code, co_name) VALUES ('AS', 'American Samoa');
INSERT INTO country (co_code, co_name) VALUES ('AD', 'Andorra');
INSERT INTO country (co_code, co_name) VALUES ('AO', 'Angola');
INSERT INTO country (co_code, co_name) VALUES ('AI', 'Anguilla');
INSERT INTO country (co_code, co_name) VALUES ('AQ', 'Antarctica');
INSERT INTO country (co_code, co_name) VALUES ('AG', 'Antigua and Barbuda');
INSERT INTO country (co_code, co_name) VALUES ('AR', 'Argentina');
INSERT INTO country (co_code, co_name) VALUES ('AM', 'Armenia');
INSERT INTO country (co_code, co_name) VALUES ('AW', 'Aruba');
INSERT INTO country (co_code, co_name) VALUES ('AU', 'Australia');
INSERT INTO country (co_code, co_name) VALUES ('AT', 'Austria');
INSERT INTO country (co_code, co_name) VALUES ('AZ', 'Azerbaijan');
INSERT INTO country (co_code, co_name) VALUES ('BS', 'Bahamas');
INSERT INTO country (co_code, co_name) VALUES ('BH', 'Bahrain');
INSERT INTO country (co_code, co_name) VALUES ('BD', 'Bangladesh');
INSERT INTO country (co_code, co_name) VALUES ('BB', 'Barbados');
INSERT INTO country (co_code, co_name) VALUES ('BY', 'Belarus');
INSERT INTO country (co_code, co_name) VALUES ('BE', 'Belgium');
INSERT INTO country (co_code, co_name) VALUES ('BZ', 'Belize');
INSERT INTO country (co_code, co_name) VALUES ('BJ', 'Benin');
INSERT INTO country (co_code, co_name) VALUES ('BM', 'Bermuda');
INSERT INTO country (co_code, co_name) VALUES ('BT', 'Bhutan');
INSERT INTO country (co_code, co_name) VALUES ('BO', 'Bolivia, Plurinational State of');
INSERT INTO country (co_code, co_name) VALUES ('BQ', 'Bonaire, Sint Eustatius and Saba');
INSERT INTO country (co_code, co_name) VALUES ('BA', 'Bosnia and Herzegovina');
INSERT INTO country (co_code, co_name) VALUES ('BW', 'Botswana');
INSERT INTO country (co_code, co_name) VALUES ('BV', 'Bouvet Island');
INSERT INTO country (co_code, co_name) VALUES ('BR', 'Brazil');
INSERT INTO country (co_code, co_name) VALUES ('IO', 'British Indian Ocean Territory');
INSERT INTO country (co_code, co_name) VALUES ('BN', 'Brunei Darussalam');
INSERT INTO country (co_code, co_name) VALUES ('BG', 'Bulgaria');
INSERT INTO country (co_code, co_name) VALUES ('BF', 'Burkina Faso');
INSERT INTO country (co_code, co_name) VALUES ('BI', 'Burundi');
INSERT INTO country (co_code, co_name) VALUES ('KH', 'Cambodia');
INSERT INTO country (co_code, co_name) VALUES ('CM', 'Cameroon');
INSERT INTO country (co_code, co_name) VALUES ('CA', 'Canada');
INSERT INTO country (co_code, co_name) VALUES ('CV', 'Cape Verde');
INSERT INTO country (co_code, co_name) VALUES ('KY', 'Cayman Islands');
INSERT INTO country (co_code, co_name) VALUES ('CF', 'Central African Republic');
INSERT INTO country (co_code, co_name) VALUES ('TD', 'Chad');
INSERT INTO country (co_code, co_name) VALUES ('CL', 'Chile');
INSERT INTO country (co_code, co_name) VALUES ('CN', 'China');
INSERT INTO country (co_code, co_name) VALUES ('CX', 'Christmas Island');
INSERT INTO country (co_code, co_name) VALUES ('CC', 'Cocos (Keeling) Islands');
INSERT INTO country (co_code, co_name) VALUES ('CO', 'Colombia');
INSERT INTO country (co_code, co_name) VALUES ('KM', 'Comoros');
INSERT INTO country (co_code, co_name) VALUES ('CG', 'Congo');
INSERT INTO country (co_code, co_name) VALUES ('CD', 'Congo, the Democratic Republic of the');
INSERT INTO country (co_code, co_name) VALUES ('CK', 'Cook Islands');
INSERT INTO country (co_code, co_name) VALUES ('CR', 'Costa Rica');
DELETE FROM country;

INSERT INTO country (co_code, co_name) VALUES ('HR', 'Croatia');
INSERT INTO country (co_code, co_name) VALUES ('CU', 'Cuba');
INSERT INTO country (co_code, co_name) VALUES ('CW', 'Curaçao');
INSERT INTO country (co_code, co_name) VALUES ('CY', 'Cyprus');
INSERT INTO country (co_code, co_name) VALUES ('CZ', 'Czech Republic');
INSERT INTO country (co_code, co_name) VALUES ('CI', 'Côte d''Ivoire');
INSERT INTO country (co_code, co_name) VALUES ('DK', 'Denmark');
INSERT INTO country (co_code, co_name) VALUES ('DJ', 'Djibouti');
INSERT INTO country (co_code, co_name) VALUES ('DM', 'Dominica');
INSERT INTO country (co_code, co_name) VALUES ('DO', 'Dominican Republic');
INSERT INTO country (co_code, co_name) VALUES ('EC', 'Ecuador');
INSERT INTO country (co_code, co_name) VALUES ('EG', 'Egypt');
INSERT INTO country (co_code, co_name) VALUES ('SV', 'El Salvador');
INSERT INTO country (co_code, co_name) VALUES ('GQ', 'Equatorial Guinea');
INSERT INTO country (co_code, co_name) VALUES ('ER', 'Eritrea');
INSERT INTO country (co_code, co_name) VALUES ('EE', 'Estonia');
INSERT INTO country (co_code, co_name) VALUES ('ET', 'Ethiopia');
INSERT INTO country (co_code, co_name) VALUES ('FK', 'Falkland Islands (Malvinas)');
INSERT INTO country (co_code, co_name) VALUES ('FO', 'Faroe Islands');
INSERT INTO country (co_code, co_name) VALUES ('FJ', 'Fiji');
INSERT INTO country (co_code, co_name) VALUES ('FI', 'Finland');
INSERT INTO country (co_code, co_name) VALUES ('FR', 'France');
INSERT INTO country (co_code, co_name) VALUES ('GF', 'French Guiana');
INSERT INTO country (co_code, co_name) VALUES ('PF', 'French Polynesia');
INSERT INTO country (co_code, co_name) VALUES ('TF', 'French Southern Territories');
INSERT INTO country (co_code, co_name) VALUES ('GA', 'Gabon');
INSERT INTO country (co_code, co_name) VALUES ('GM', 'Gambia');
INSERT INTO country (co_code, co_name) VALUES ('GE', 'Georgia');
INSERT INTO country (co_code, co_name) VALUES ('DE', 'Germany');
INSERT INTO country (co_code, co_name) VALUES ('GH', 'Ghana');
INSERT INTO country (co_code, co_name) VALUES ('GI', 'Gibraltar');
INSERT INTO country (co_code, co_name) VALUES ('GR', 'Greece');
INSERT INTO country (co_code, co_name) VALUES ('GL', 'Greenland');
INSERT INTO country (co_code, co_name) VALUES ('GD', 'Grenada');
INSERT INTO country (co_code, co_name) VALUES ('GP', 'Guadeloupe');
INSERT INTO country (co_code, co_name) VALUES ('GU', 'Guam');
INSERT INTO country (co_code, co_name) VALUES ('GT', 'Guatemala');
INSERT INTO country (co_code, co_name) VALUES ('GG', 'Guernsey');
INSERT INTO country (co_code, co_name) VALUES ('GN', 'Guinea');
INSERT INTO country (co_code, co_name) VALUES ('GW', 'Guinea-Bissau');
INSERT INTO country (co_code, co_name) VALUES ('GY', 'Guyana');
INSERT INTO country (co_code, co_name) VALUES ('HT', 'Haiti');
INSERT INTO country (co_code, co_name) VALUES ('HM', 'Heard Island and McDonald Islands');
INSERT INTO country (co_code, co_name) VALUES ('VA', 'Holy See (Vatican City State)');
INSERT INTO country (co_code, co_name) VALUES ('HN', 'Honduras');
INSERT INTO country (co_code, co_name) VALUES ('HK', 'Hong Kong');
INSERT INTO country (co_code, co_name) VALUES ('HU', 'Hungary');
INSERT INTO country (co_code, co_name) VALUES ('IS', 'Iceland');
INSERT INTO country (co_code, co_name) VALUES ('IN', 'India');
INSERT INTO country (co_code, co_name) VALUES ('ID', 'Indonesia');
INSERT INTO country (co_code, co_name) VALUES ('IR', 'Iran, Islamic Republic of');
INSERT INTO country (co_code, co_name) VALUES ('IQ', 'Iraq');
INSERT INTO country (co_code, co_name) VALUES ('IE', 'Ireland');
INSERT INTO country (co_code, co_name) VALUES ('IM', 'Isle of Man');
INSERT INTO country (co_code, co_name) VALUES ('IL', 'Israel');
INSERT INTO country (co_code, co_name) VALUES ('IT', 'Italy');
INSERT INTO country (co_code, co_name) VALUES ('JM', 'Jamaica');
INSERT INTO country (co_code, co_name) VALUES ('JP', 'Japan');
INSERT INTO country (co_code, co_name) VALUES ('JE', 'Jersey');
INSERT INTO country (co_code, co_name) VALUES ('JO', 'Jordan');
INSERT INTO country (co_code, co_name) VALUES ('KZ', 'Kazakhstan');
INSERT INTO country (co_code, co_name) VALUES ('KE', 'Kenya');
INSERT INTO country (co_code, co_name) VALUES ('KI', 'Kiribati');
INSERT INTO country (co_code, co_name) VALUES ('KP', 'Democratic People''s Republic of Korea');
INSERT INTO country (co_code, co_name) VALUES ('KR', 'Republic of Korea');
INSERT INTO country (co_code, co_name) VALUES ('KW', 'Kuwait');
INSERT INTO country (co_code, co_name) VALUES ('KG', 'Kyrgyzstan');
INSERT INTO country (co_code, co_name) VALUES ('LA', 'Lao People''s Democratic Republic');
INSERT INTO country (co_code, co_name) VALUES ('LV', 'Latvia');
INSERT INTO country (co_code, co_name) VALUES ('LB', 'Lebanon');
INSERT INTO country (co_code, co_name) VALUES ('LS', 'Lesotho');
INSERT INTO country (co_code, co_name) VALUES ('LR', 'Liberia');
INSERT INTO country (co_code, co_name) VALUES ('LY', 'Libya');
INSERT INTO country (co_code, co_name) VALUES ('LI', 'Liechtenstein');
INSERT INTO country (co_code, co_name) VALUES ('LT', 'Lithuania');
INSERT INTO country (co_code, co_name) VALUES ('LU', 'Luxembourg');
INSERT INTO country (co_code, co_name) VALUES ('MO', 'Macao');
INSERT INTO country (co_code, co_name) VALUES ('MK', 'Macedonia, the Former Yugoslav Republic of');
INSERT INTO country (co_code, co_name) VALUES ('MG', 'Madagascar');
INSERT INTO country (co_code, co_name) VALUES ('MW', 'Malawi');
INSERT INTO country (co_code, co_name) VALUES ('MY', 'Malaysia');
INSERT INTO country (co_code, co_name) VALUES ('MV', 'Maldives');
INSERT INTO country (co_code, co_name) VALUES ('ML', 'Mali');
INSERT INTO country (co_code, co_name) VALUES ('MT', 'Malta');
INSERT INTO country (co_code, co_name) VALUES ('MH', 'Marshall Islands');
INSERT INTO country (co_code, co_name) VALUES ('MQ', 'Martinique');
INSERT INTO country (co_code, co_name) VALUES ('MR', 'Mauritania');
INSERT INTO country (co_code, co_name) VALUES ('MU', 'Mauritius');
INSERT INTO country (co_code, co_name) VALUES ('YT', 'Mayotte');
INSERT INTO country (co_code, co_name) VALUES ('MX', 'Mexico');
INSERT INTO country (co_code, co_name) VALUES ('FM', 'Micronesia, Federated States of');
INSERT INTO country (co_code, co_name) VALUES ('MD', 'Moldova, Republic of');
INSERT INTO country (co_code, co_name) VALUES ('MC', 'Monaco');
INSERT INTO country (co_code, co_name) VALUES ('MN', 'Mongolia');
INSERT INTO country (co_code, co_name) VALUES ('ME', 'Montenegro');
INSERT INTO country (co_code, co_name) VALUES ('MS', 'Montserrat');
INSERT INTO country (co_code, co_name) VALUES ('MA', 'Morocco');
INSERT INTO country (co_code, co_name) VALUES ('MZ', 'Mozambique');
INSERT INTO country (co_code, co_name) VALUES ('MM', 'Myanmar');
INSERT INTO country (co_code, co_name) VALUES ('NA', 'Namibia');
INSERT INTO country (co_code, co_name) VALUES ('HR', 'Croatia');
INSERT INTO country (co_code, co_name) VALUES ('CU', 'Cuba');
INSERT INTO country (co_code, co_name) VALUES ('CW', 'Curaçao');
INSERT INTO country (co_code, co_name) VALUES ('CY', 'Cyprus');
INSERT INTO country (co_code, co_name) VALUES ('CZ', 'Czech Republic');
INSERT INTO country (co_code, co_name) VALUES ('CI', 'Côte d''Ivoire');
INSERT INTO country (co_code, co_name) VALUES ('DK', 'Denmark');
INSERT INTO country (co_code, co_name) VALUES ('DJ', 'Djibouti');
INSERT INTO country (co_code, co_name) VALUES ('DM', 'Dominica');
INSERT INTO country (co_code, co_name) VALUES ('DO', 'Dominican Republic');
INSERT INTO country (co_code, co_name) VALUES ('EC', 'Ecuador');
INSERT INTO country (co_code, co_name) VALUES ('EG', 'Egypt');
INSERT INTO country (co_code, co_name) VALUES ('SV', 'El Salvador');
INSERT INTO country (co_code, co_name) VALUES ('GQ', 'Equatorial Guinea');
INSERT INTO country (co_code, co_name) VALUES ('ER', 'Eritrea');
INSERT INTO country (co_code, co_name) VALUES ('EE', 'Estonia');
INSERT INTO country (co_code, co_name) VALUES ('ET', 'Ethiopia');
INSERT INTO country (co_code, co_name) VALUES ('FK', 'Falkland Islands (Malvinas)');
INSERT INTO country (co_code, co_name) VALUES ('FO', 'Faroe Islands');
INSERT INTO country (co_code, co_name) VALUES ('FJ', 'Fiji');
INSERT INTO country (co_code, co_name) VALUES ('FI', 'Finland');
INSERT INTO country (co_code, co_name) VALUES ('FR', 'France');
INSERT INTO country (co_code, co_name) VALUES ('GF', 'French Guiana');
INSERT INTO country (co_code, co_name) VALUES ('PF', 'French Polynesia');
INSERT INTO country (co_code, co_name) VALUES ('TF', 'French Southern Territories');
INSERT INTO country (co_code, co_name) VALUES ('GA', 'Gabon');
INSERT INTO country (co_code, co_name) VALUES ('GM', 'Gambia');
INSERT INTO country (co_code, co_name) VALUES ('GE', 'Georgia');
INSERT INTO country (co_code, co_name) VALUES ('DE', 'Germany');
INSERT INTO country (co_code, co_name) VALUES ('GH', 'Ghana');
INSERT INTO country (co_code, co_name) VALUES ('GI', 'Gibraltar');
INSERT INTO country (co_code, co_name) VALUES ('GR', 'Greece');
INSERT INTO country (co_code, co_name) VALUES ('GL', 'Greenland');
INSERT INTO country (co_code, co_name) VALUES ('GD', 'Grenada');
INSERT INTO country (co_code, co_name) VALUES ('GP', 'Guadeloupe');
INSERT INTO country (co_code, co_name) VALUES ('GU', 'Guam');
INSERT INTO country (co_code, co_name) VALUES ('GT', 'Guatemala');
INSERT INTO country (co_code, co_name) VALUES ('GG', 'Guernsey');
INSERT INTO country (co_code, co_name) VALUES ('GN', 'Guinea');
INSERT INTO country (co_code, co_name) VALUES ('GW', 'Guinea-Bissau');
INSERT INTO country (co_code, co_name) VALUES ('GY', 'Guyana');
INSERT INTO country (co_code, co_name) VALUES ('HT', 'Haiti');
INSERT INTO country (co_code, co_name) VALUES ('HM', 'Heard Island and McDonald Islands');
INSERT INTO country (co_code, co_name) VALUES ('VA', 'Holy See (Vatican City State)');
INSERT INTO country (co_code, co_name) VALUES ('HN', 'Honduras');
INSERT INTO country (co_code, co_name) VALUES ('HK', 'Hong Kong');
INSERT INTO country (co_code, co_name) VALUES ('HU', 'Hungary');
INSERT INTO country (co_code, co_name) VALUES ('IS', 'Iceland');
INSERT INTO country (co_code, co_name) VALUES ('IN', 'India');
INSERT INTO country (co_code, co_name) VALUES ('ID', 'Indonesia');
INSERT INTO country (co_code, co_name) VALUES ('IR', 'Iran, Islamic Republic of');
INSERT INTO country (co_code, co_name) VALUES ('IQ', 'Iraq');
INSERT INTO country (co_code, co_name) VALUES ('IE', 'Ireland');
INSERT INTO country (co_code, co_name) VALUES ('IM', 'Isle of Man');
INSERT INTO country (co_code, co_name) VALUES ('IL', 'Israel');
INSERT INTO country (co_code, co_name) VALUES ('IT', 'Italy');
INSERT INTO country (co_code, co_name) VALUES ('JM', 'Jamaica');
INSERT INTO country (co_code, co_name) VALUES ('JP', 'Japan');
INSERT INTO country (co_code, co_name) VALUES ('JE', 'Jersey');
INSERT INTO country (co_code, co_name) VALUES ('JO', 'Jordan');
INSERT INTO country (co_code, co_name) VALUES ('KZ', 'Kazakhstan');
INSERT INTO country (co_code, co_name) VALUES ('KE', 'Kenya');
INSERT INTO country (co_code, co_name) VALUES ('KI', 'Kiribati');
INSERT INTO country (co_code, co_name) VALUES ('KP', 'Democratic People''s Republic of Korea');
INSERT INTO country (co_code, co_name) VALUES ('KR', 'Republic of Korea');
INSERT INTO country (co_code, co_name) VALUES ('KW', 'Kuwait');
INSERT INTO country (co_code, co_name) VALUES ('KG', 'Kyrgyzstan');
INSERT INTO country (co_code, co_name) VALUES ('LA', 'Lao People''s Democratic Republic');
INSERT INTO country (co_code, co_name) VALUES ('LV', 'Latvia');
INSERT INTO country (co_code, co_name) VALUES ('LB', 'Lebanon');
INSERT INTO country (co_code, co_name) VALUES ('LS', 'Lesotho');
INSERT INTO country (co_code, co_name) VALUES ('LR', 'Liberia');
INSERT INTO country (co_code, co_name) VALUES ('LY', 'Libya');
INSERT INTO country (co_code, co_name) VALUES ('LI', 'Liechtenstein');
INSERT INTO country (co_code, co_name) VALUES ('LT', 'Lithuania');
INSERT INTO country (co_code, co_name) VALUES ('LU', 'Luxembourg');
INSERT INTO country (co_code, co_name) VALUES ('MO', 'Macao');
INSERT INTO country (co_code, co_name) VALUES ('MK', 'Macedonia, the Former Yugoslav Republic of');
INSERT INTO country (co_code, co_name) VALUES ('MG', 'Madagascar');
INSERT INTO country (co_code, co_name) VALUES ('MW', 'Malawi');
INSERT INTO country (co_code, co_name) VALUES ('MY', 'Malaysia');
INSERT INTO country (co_code, co_name) VALUES ('MV', 'Maldives');
INSERT INTO country (co_code, co_name) VALUES ('ML', 'Mali');
INSERT INTO country (co_code, co_name) VALUES ('MT', 'Malta');
INSERT INTO country (co_code, co_name) VALUES ('MH', 'Marshall Islands');
INSERT INTO country (co_code, co_name) VALUES ('MQ', 'Martinique');
INSERT INTO country (co_code, co_name) VALUES ('MR', 'Mauritania');
INSERT INTO country (co_code, co_name) VALUES ('MU', 'Mauritius');
INSERT INTO country (co_code, co_name) VALUES ('YT', 'Mayotte');
INSERT INTO country (co_code, co_name) VALUES ('MX', 'Mexico');
INSERT INTO country (co_code, co_name) VALUES ('FM', 'Micronesia, Federated States of');
INSERT INTO country (co_code, co_name) VALUES ('MD', 'Moldova, Republic of');
INSERT INTO country (co_code, co_name) VALUES ('MC', 'Monaco');
INSERT INTO country (co_code, co_name) VALUES ('MN', 'Mongolia');
INSERT INTO country (co_code, co_name) VALUES ('ME', 'Montenegro');
INSERT INTO country (co_code, co_name) VALUES ('MS', 'Montserrat');
INSERT INTO country (co_code, co_name) VALUES ('MA', 'Morocco');
INSERT INTO country (co_code, co_name) VALUES ('MZ', 'Mozambique');
INSERT INTO country (co_code, co_name) VALUES ('MM', 'Myanmar');
INSERT INTO country (co_code, co_name) VALUES ('NA', 'Namibia');
